### PR TITLE
Added potential fix for iOS devices. 

### PR DESCRIPTION
**Pull request by mparker11**
Using FileReader API to convert blob into data uri with base64 encoding, allowing iOS devices to open the links.

### CODE REVIEW

**Comment by Ruffio** [comment]
Is this still an issue?

**Comment by mparker11** [comment]
I don't know. The project I used it for is long gone. But for future users, is it possible for you to test and accept/decline the pull request?

**Comment by Ruffio** [comment]
@mparker11  this should be closed.

**Comment by jimmywarting** [comment]
> this commit doesn't fix the problem.

closing this then

**Pull request closed without merging**
