### PR TITLE
Workaround for Windows phone 10 Edge bug (#193)

### PR DESCRIPTION
**Pull request by MartinHlavna**
Degradation to `<a download>` attribute in windows phone 10. 

This is submitted as issue #193  . Since MS is not giving any progress on this issue, I have created workaround that sniffs user agent to detect windows phone 10. On these devices is then used "a download" attribute. However this solution is not able to override file name, which will save the the file as blob UUID. 

This is also submitted as issue

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6594876/

but is has been lately marked as fixed.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Hmm, instead of sniffing. How about using download attribute as first choice if it's supported? Or is IE's save method still preferred over create object url?

**Comment by MartinHlavna** [comment]
Well, I think It is good to remain using IE's save method for now if it is possible. We will see if the download attribute in next update will really be fixed and how stable the fix will be. If it will be good then this may be a good idea. 

But the problem may be Edge / IE users that dont upgrade / they will be saving with the UUID as the name.

**Comment by Ruffio** [comment]
Should this issue be merged?

**Comment by ThomasPe** [comment]
This would be great!

**Comment by eligrey** [comment]
Yeah, I will merge this. It looks like it needs rebased though.

**Comment by MartinHlavna** [comment]
I will look onto rebasing as soon as I can

**Comment by Ruffio** [comment]
@MartinHlavna how is the rebasing going?

**Comment by MartinHlavna** [comment]
I didn't have time first and then forgot about it. Thanks for bringing this up.

**Comment by Ruffio** [comment]
@MartinHlavna how is the rebasing going?

**Comment by Ruffio** [comment]
@eligrey this PR should be rejected as it is incomplete and author has failed to respond for three months...

**Pull request closed without merging**
