### PR TITLE
V2-rc1

### LINKED ISSUE #193: Not work with lumia!
Hi,
i've integrated here: https://laltroweb.it/tools/password-generator/
## (is a pure javascript form - no php, so - filesaver is a good script for save string)

work with all my browser: chrome, firefox, ie and edge on windows 10, but not in lumia browser (is a ie mobile).

help or bugfix is must appreciated :)

regards,
S.N.

### LINKED ISSUE #346: Opening up in same Tab in Safari on iPhone
In Safari on my iPhone / iPad the File (PDF) does not open up in a new Window but in the same Window, so I have to navigate back to the Page where I came from.

It should open up in a new Tab as described.

_If you can't confirm this issue I can show you, but I don't want to publish the URL right here._

### LINKED ISSUE #382: Unable to dispatch click on Chrome/Safari
I am getting the following error while calling saveAs

```
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
```

file-saver@^1.3.3
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Safari Version 11.0.1 (12604.3.5.1.1)
OSX Sierra 10.12.6 (16G1036)

It goes away if I revert https://github.com/eligrey/FileSaver.js/pull/152 partially with

```patch
+++      var event = document.createEvent("MouseEvents");
+++      event.initMouseEvent("click", true, true, window, 0, 0, 0, 80, 20, false, false, false, false, 0, null);
---      var event = new MouseEvent("click");

```

I get that [initMouseEvent is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent) but I found no other workaround.

In stackoverflow [someone points](https://stackoverflow.com/a/42064469/30948) points that maybe there are some properties missing with using `MouseEvent` constructor. But, as [somebody else](https://stackoverflow.com/questions/41920266/dispatchevent-causes-error-failed-to-execute-dispatchevent-on-eventtarget-p#comment76691039_42064469), I couldn't solve the issue with those properties.

### LINKED ISSUE #409: [1.3.6+] Bower distribution is empty
When installing version 1.3.6 from Bower, the directory contains only `bower.json` and `LICENSE.md`.

### LINKED ISSUE #415: v1.3.6 not available on npm?
npm is still on v1.3.4

### LINKED ISSUE #416: dist/FileSaver listed in package.json in FILES
The `dist` directory is not included in the repo but is the entrypoint to the 1.3.x releases!

### LINKED ISSUE #432: remove BOM?
https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L69 notes that the auto_bom function "prepend[s] BOM for UTF-8 XML and text/* types (including HTML)", but UTF8-encoded documents don't need a byte ordering mark, since UTF8 does not consist of "ordered bytes" like UTF16/32, but is a byte-aligned bit sequence instead, with the same ordering on all systems.

### LINKED ISSUE #449: Lib throws error when imported inside a service worker
Currently on the project that I'm working on, there's a build process for the service worker used in the application, and one of the files used by the service worker is importing the lib, although the lib is not used inside the service worker, it throws an error when executing the service worker script, which is:  

`TypeError: Cannot read property 'createElementNS' of undefined`

### PR DESCRIPTION
**Pull request by jimmywarting**
I think the issues have been overwhelmed by reports and i would want to try to close most of them once and for good to give it a more clean slate.  (Many issues have been stale for a long time and i can't determinate if it's relevant anymore. Would like to close all (most) issue for being too old. Anything still an issue can be reopen or made as a new issue)

I have try to go throught all of the issues. Trying to clean up things and rewrite the hole thing from the ground up to try and fix most pr & issues for 3 days now 

here are some changes:

- Removed the hole event thing since nobody is using it anyway
  - ppl only do `saveAs(...)` so there is no reason to return anything
  - Detecting any of those event have never or will never be possible to detect (onwrite, onend, etc) since the spec was abandoned. 
- Removed the demos since it's rather old (lets keep it to readme's wiki's and jsfiddles)
  - Means less maintainability
- Removed date/version from top of the file since it easy to forget to change
- Dosen't crash in web workers
- Support saving urls (#260  with workarounds for cross origin)
  - https://stackoverflow.com/q/49474775/1008999
- Uses babel universal module pattern (UMD)
- provides source map now as well.
- use `a[download]` before msSaveAs (#193, #294)
- removed dist from .gitignore (npm uses it if it don't find a .npmignore)
- use conditional function instad of trying every possible solution in one flow (future detection) 
- noAutoBom switched to autoBom (#432 makes autoBom optional)
- no longer use dispatchEvent since there are new and depricated event constructors that works differently (#382)
- opens up a new popup (tab) directly for the fallback method since the FileReader is async
  - once the reader gets the final dataURI it assigns the url of the popup (#346) and sets the popup to null (#460)
- removed the explicitly MSIE [1-9] check since blob.js can polyfill them but i doubt anyone are still using such old browser anymore that made the check necessary. 

closes #382
closes #460
closes #459
closes #294
closes #193
closes #260
closes #142
closes #449
closes #432
closes #416
closes #415
closes #409
closes #346
closes #260 
and possible more

hopes to solve (#453, #451, #445, #441, #438, #436, #433, #434, #431, #408, #427, #423, #414, #422, #414, #248 and possible more)

### CODE REVIEW

**Comment by Ruffio** [comment]
Cool. Can't wait to test it when release :-) Makes good senge to start all over.

**Comment by jimmywarting** [comment]
@Ruffio glad to here, will see if @eligrey is onboard with this as well, if so I might publish push it to https://www.npmjs.com/package/file-saver as `-rc.1` so ppl can test it first.

Would be grate if you could test it out as much as possible on different browsers. Both url and blobs. and if the umd pattern works okey with import/require etc, I don't have IE/Edge on Mac so...

**Comment by eligrey** [comment]
The PR description sounds good to me! I have yet to review the code and will try to do that tonight.

**Comment by jimmywarting** [comment]
If you don't like the code formatting or something is done incorrectly, by all mean fork the PR, or write code review and i will change it.

I mostly stick to what StandardJS dose but i don't enforce a Linting as rules are often broken or things don't look the way you want it to be my and bitinn two cents: https://github.com/bitinn/node-fetch/issues/303#issuecomment-310267412

**Comment by jimmywarting** [comment]
maybe thinking we can maybe squeeze in one small `.d.ts` file also for type definition (it's just one function)
what i don't want to do is to write the code with typescript

Never liked typescript (only adds overhead and don't work in browser or node as it is. always need a extra compile step)

**Comment by eligrey** [comment]
I'll do my review tomorrow.

**Comment by eligrey** [comment]
lgtm

**Pull request merged**
