### PR TITLE
Fix: Change deprecated synchronous request to asynchronous

### LINKED ISSUE #574: Chrome gives me a warning in Angular app
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### LINKED ISSUE #655: corsEnabled uses deprecated synchronous xhr
>  Starting in Firefox 30, synchronous requests on the main thread have been deprecated due to their negative impact on performance and the user experience. Therefore, the async parameter may not be false except in a Worker.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open 

From FileSaver.js:
```
function corsEnabled (url, opts) {
  var xhr = new XMLHttpRequest()
  // use sync to avoid popup blocker
  xhr.open('HEAD', url, false)
  try {
    xhr.send()
  } catch (e) {}
  return xhr.status >= 200 && xhr.status <= 299
}
```

### PR DESCRIPTION
**Pull request by igneosaur**
Changes the [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open#parameters) synchronous `HEAD` request for an asynchronous one, removing the console warning.

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

Fixes #655
Fixes #574

### CODE REVIEW

**Comment by mnlmaier** [comment]
What's the status on this PR? Currently using this for a project, and getting rid of the console.warn would certainly be nice :)

**Comment by igneosaur** [comment]
Not sure mate. There hasn't been a merge on this project for almost a year so I wouldn't hold your breath.

**Comment by capegreg** [comment]
Please fix. There's no alternative than to get this fixed. All flags to disable synchronous XMLHTTPRequest open calls have been removed from Chrome. Edge is still behind on updates, but expect changes here , too.

Starting from Chrome version 88, the --disable-sync-xhr flag that was previously used to allow synchronous XHR calls has been removed. This means that synchronous XHR requests are no longer supported in Chrome, and there is no longer a way to enable them using command-line flags or other configuration settings.

The reason for this change is that synchronous XHR requests have been deprecated for some time due to their potential to cause performance and stability issues, and are no longer supported in modern web APIs such as the Fetch API and the newer XMLHttpRequest (XHR) API.

Therefore, it's recommended that web developers avoid using synchronous XHR requests in their applications and instead use asynchronous requests, which are better suited to modern web development practices and are widely supported across different browsers and platforms.

**Comment by jimmywarting** [comment]
This fix will not work for 1 reason:

You have only removed the sync option in the `xhr.open()`
but the function `corsEnabled` still expect and returns a boolean
at this point the solution you have written then status code will always be unknown to you so `xhr.status` will always be `0` and return false. which leads to always using `a[download]` instead of never calling the download-ajax method...

The original reason for wanting to use the ajax-download method approach instead of using `a[download]` is b/c of: 

> - download only works for [same-origin URLs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), or the blob: and data: schemes.
> 
> ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

The other related code that calls `corsEnabled()` would have to either use a callback or a promise approach too.

**Pull request closed without merging**
