### PR TITLE
Workaround for downloading application/octet-stream in Safari

### PR DESCRIPTION
**Pull request by antelle**
I have added workaround which works in Safari (I have tested it in Safari 9, 8 and 7).
http://jsbin.com/tefoqo/2/edit?html,js,output
Limitation: the file is downloaded but the name is always Unknown. I have not found a way to change it but the ability to download file is better than just throw error `Failed to load resource: Frame load interrupted`.
This is related to issue #12 but resolves is only partially as the file is downloaded with undesired name.

### CODE REVIEW

**Comment by eligrey** [comment]
Nice, thanks for the solution of using the `attachment/file` media type. I will accept this pullreq after you address my two comments.

**Comment by antelle** [comment]
Yes, thank you for correction!
encodeURI was still here because I was testing before and forgot to remove it.
Also I have fixed safari detection as `typeof safari` doesn't work for me.
Pushed all the changes, this PR has been updated.
Also updated dist file.

**Comment by antelle** [comment]
You should update script in readme file, the correct one is:
```bash
uglifyjs FileSaver.js --mangle --comments /@source/ > FileSaver.min.js
```
With new uglifyjs2, the script from readme doesn't mangle names.

**Comment by eligrey** [comment]
Also you can include your readme changes with this pullreq.

**Comment by antelle** [comment]
Fixed your comment and added the missing option to readme.

**Comment by eligrey** [comment]
Thanks.

**Comment by lslzl3000** [comment]
Is there any way to solve 'Unknown' file name?

**Comment by antelle** [comment]
I haven't found any workaround for this. I think, you may achieve some results if you investigate that error which is generated from blob download.

**Pull request merged**
