### PR TITLE
Catching an exception on Send. This happens when request for HEAD ret…

### PR DESCRIPTION
**Pull request by rybama**
…urns 405 Method Not Allowed. Instead of error http status, this may throw an exception. Return false and fallback to link download.

### CODE REVIEW

**Comment by jimmywarting** [comment]
In which browser dose it throw an error?
i only get a error log.

Skärmavbild 2019-03-19 kl  11 15 56

the code still runs after it

**Comment by rybama** [comment]
I'm gettin exception (NetworkError) on Chrome.

**Comment by jimmywarting** [comment]
Mind sharing the url you are trying so that i can test it?
also dose it throw with the httpbin url i used?

**Comment by rybama** [comment]
httpbin url you send doesn't throw an exception. This api endpoint for example will throw an exception https://portal.radar.f-secure.com/api/latest/productinfo  (works for GET). I'm now more convinced that send throws an exception when certain API doesn't implement HEAD verb.

**Comment by jimmywarting** [comment]
hmm, when making a sync request to any url that don't implement CORS support seems to throw an error

**Comment by rybama** [comment]
So, is it good to merge it?

**Comment by rybama** [comment]
@jimmywarting  kindly reminder :) ping :)

**Comment by rybama** [comment]
@jimmywarting I would like to ask to for clear comment if you intend to accept this change or not. We rely on the forked project in the npm dependencies in our project right now which I would like to remove.

**Comment by jimmywarting** [comment]
Sure. Will try to do it later todayy

**Comment by jimmywarting** [comment]
released this with v2.0.2 on npm now

**Comment by rybama** [comment]
thanks!

**Comment by xiaoluntian** [comment]
hi why use a HEAD request,not the GET request replace.If crosed enabled,continue to use blob to download, if not, go to the other side.

**Pull request merged**
