### PR TITLE
click does only accept one parameter

### PR DESCRIPTION
**Pull request by arasabbasi**

### CODE REVIEW

**Comment by jimmywarting** [comment]
> click does only accept one parameter

So lets take advantage of it...

**Comment by arasabbasi** [comment]
What do you mean?

**Comment by jimmywarting** [comment]
Just an old trick i learned from https://github.com/jed/140bytes/wiki/Byte-saving-techniques#reuse-parenthesis-of-the-function-call

Normally i never write code to use unused parenthesis of the function calls. but this is a internal function that i had control over what arguments where used and i saw a opportunity to use `? :` instead of writing a hole `if...else` block.

I have seen this trick being used by smart code minifier

**Comment by arasabbasi** [comment]
Hmm. Well. And I guess an optimizer would not realize this. Tbh not very clean in the means of Clean Code, but I get why you do it.

**Pull request closed without merging**
