### PR TITLE
Fixed link to demo site in README.md

### PR DESCRIPTION
**Pull request by FriendFX**

### CODE REVIEW

**Comment by eligrey** [comment]
I'll get the demo back up soon.

**Comment by FriendFX** [comment]
@eligrey Is there a need for a separate site? The Github CDN seems to work fine, or am I missing something?

**Comment by eligrey** [comment]
cdn.rawgit.com is not the 'GitHub CDN', and is not even run by GitHub. The proper use of the GitHub CDN is to use GitHub pages. Anyways, it will be back up this week. I've been moving servers for all of my websites and I'll be done soon.

**Comment by jimmywarting** [comment]
It works now, so it can be closed...
@eligrey Would you like to move the demo to github pages?

**Pull request closed without merging**
