### PR TITLE
be consistant with define and exports

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by jimmywarting** [comment]
This wouldn't be backward compatible?

**Comment by graingert** [comment]
Version 2?

**Comment by eligrey** [comment]
@graingert You didn't minify with UglifyJS

**Comment by graingert** [comment]
Yes I did...

**Comment by graingert** [comment]
Probably best not to get contributors to run the build as it makes merges impossible. Best to just run the build before you tag

**Comment by eligrey** [comment]
@graingert Yeah that makes sense. I guess we should rethink minified file distribution.

**Comment by graingert** [comment]
@eligrey any update on this?

**Comment by eligrey** [comment]
Fixed by #391

**Pull request closed without merging**
