### PR TITLE
Add safe module name to avoid requireJS errors

### PR DESCRIPTION
**Pull request by zky829**
If a safe module name is not defined for requireJS, it will throw a "Mismatched anonymous define() modules..." error in the browser. I just made up a very generic-sounding module name, welcoming suggestions!

### CODE REVIEW

**Comment by kashiif** [comment]
+1.

**Comment by jimmywarting** [comment]
@kashiif use reactions instead of +1

**Comment by kashiif** [comment]
cool, I didn't know that @jimmywarting. Thanks

**Comment by bbadeaux-ias** [comment]
+1. This is breaking Karma tests for us!

**Comment by eligrey** [comment]
@zky829 Rebase off the current master and I'll accept a PR with the value `"FileSaver.js"`.

**Comment by zky829** [comment]
@eligrey: Done!

**Comment by bbadeaux-ias** [comment]
Woot!!! THanks man!

**Comment by bbadeaux-ias** [comment]
You da man! Thank you sir!!


Bill Badeaux
Integral Ad Science
Austin, TX
713.806.6699

**Comment by sffc** [comment]
This change quietly broke my application when I rolled in updates.  I had set up my require.js shimmed up to give the module a name, and now the name I assigned ("filesaver") was no longer being found.

In addition, it is bad practice to give your module a name ending with `.js`.  That breaks the require.js path loader by design:

https://github.com/requirejs/requirejs/issues/1560

My not-so-great workaround for the time being is to link against 1.3.2, the latest version of require.js before this change.

I would send a PR to fix this, but #445 and #453 are also blockers, so for now I'm going to stick with the version that works.

**Pull request merged**
