### PR TITLE
readme: info on import/require

### PR DESCRIPTION
**Pull request by tchakabam**
info that may be useful for others :)

### CODE REVIEW

**Comment by Ruffio** [comment]
@eligrey should this be merged?

**Comment by Ruffio** [comment]
@eligrey should this be merged?

**Comment by out0mana** [comment]
This is helpful. +1 to merge.

**Comment by Ruffio** [comment]
@eligrey can this be merged? It is just a small update for the docs., that helps people :-)

**Comment by tchakabam** [comment]
hey. not sure anymore myself why i made this PR. The relevant info is already in the examples further up in the actual readme. Maybe I missed that or was using an older version which didn't have that info. I guess having this now is a bit redundant with the examples given in the readme already. Basically, it was just about giving info on the, admitted, very simple API, which I was missing apparently. 

Other than that, this is just common JS know-how and various examples how to require something, not necessarily specific to this lib, so not sure it needs to be put in the readme after all :) Feel free to close this.

**Comment by Ruffio** [comment]
Then just delete this PR

**Pull request closed without merging**
