### PR TITLE
This closes #195

### LINKED ISSUE #195: running FileSaver in PhantomJs fails
Running saveAs

ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/6044259D-89C8-4116-889C-6AE74FC166BA.dmp

ERROR [launcher]: PhantomJS crashed.

### PR DESCRIPTION
**Pull request by superdecimal**

### CODE REVIEW

**Comment by eligrey** [comment]
`document.createEvent` is deprecated and will not be available in future browsers.

**Comment by jimmywarting** [comment]
Close? Nobody is using phantomjs except developers for testing purpose. Phantomjs has low maintenance and haven't gotten any upgrade in a long while and still use a very old webkit version.

Beside how are you going to save a file in a windowless browser?

**Comment by jimmywarting** [comment]
You should use phantomjs way of writing files to the file system http://phantomjs.org/api/fs/method/write.html

**Comment by eligrey** [comment]
@jimmywarting thanks for pointing out a few issues that needed closing. I've been very busy with commercial projects so I haven't had a lot of time to go through the FileSaver.js issue backlog.

If you want to be an issues moderator, ask and I'll give you access :)

**Comment by jimmywarting** [comment]
@ellgrey Sure, I would like to help

**Comment by eligrey** [comment]
@jimmywarting added

**Pull request closed without merging**
