### PR TITLE
Fix accidental rewrite of global saveAs function

### LINKED ISSUE #498: global saveAs function is not kept properly when filesaver js is loaded twice
In FileSaver.js, it seems that the line that starts with: `var saveAs = _global.saveAs ||` has the intention to keep the current saveAs function if it is already defined. Unfortunately that is not the case because after the || there is a ternary function which is missing partheses.

### PR DESCRIPTION
**Pull request by segovia**
The change is just to put parentheses around the code after `var saveAs = _global.saveAs ||`
and then indent it properly.

closes #498

### CODE REVIEW

**Comment by eligrey** [comment]
I'm not sure what you are trying to accomplish. Would you mind explaining in more detail?

**Comment by eligrey** [comment]
I'm not sure of what you are trying to accomplish. Would you mind explaining in more detail?

**Comment by segovia** [comment]
Basically, we had an issue with the following line of code.

Currently it is:
`var saveAs = _global.saveAs || (typeof window !== 'object' || window !== _global) ? function saveAs () { /* noop */ } : (some other stuff)`

the problem with the code above is, when `_global.saveAs` is truthy, the expression resolves to the noop function. This happens because `||` has higher precedence than `?`. Below, I rewrite the expression with exactly the same semantics as the original, just adding the redundant parentheses.

`var saveAs = (_global.saveAs || (typeof window !== 'object' || window !== _global)) ? function saveAs () { /* noop */ } : (some other stuff)`

I assume that its not the intention of the code to define `saveAs` as a noop function if `_global.saveAs` is already defined. So the fix is to simply add parentheses in the right place, to make sure the `global.saveAs` function is kept if it is already defined. So my change is basically adding parentheses after the first `||` to group everything after it.

`var saveAs = _global.saveAs || ((typeof window !== 'object' || window !== _global) ? function saveAs () { /* noop */ } : (some other stuff))`

The actual commit is harder to read because of formatting, but I just added those parentheses.

**Comment by segovia** [comment]
I added the /dist files to the commit since I just realized they were missing

**Comment by eligrey** [comment]
I'll review this sometime next week. Sorry for the wait!

**Comment by segovia** [comment]
Thanks, np!

**Comment by segovia** [comment]
> I'll review this sometime next week. Sorry for the wait!

Any chance of accepting this pull request? If you need any changes, just let me know :)

**Comment by rayhidayat** [comment]
I independently identified this same issue, figured out the fix, and was about to open an identical issue and pull request before I saw this was the same. This definitely is the correct fix. FileSaver doesn't work with webpack without this fix. I don't know why webpack loads it twice, but it does, and I imagine it's pretty common for people to use webpack with this library.

**Comment by liborm85** [comment]
@eligrey @jimmywarting Can you release this in the new version?
It causes problems in pdfmake - https://github.com/bpampuch/pdfmake/issues/1634

**Comment by jimmywarting** [comment]
done

**Pull request merged**
