### PR TITLE
Revert "Use FileReader in macOS native apps using WebKit"

### LINKED ISSUE #624: Latest commit breaks file download in Chrome
This recent commit (https://github.com/eligrey/FileSaver.js/commit/7a8ff3cc6ae717b6c7628b3c280a5c593c2206ee) has broken downloads in Chrome. 

When I use the script from Tampermonkey to download a text file a new tab opens with the text "downloading..." and the file is downloaded with the generic filename "download", ignoring the filename set in the script.

I'm using Chrome Version 80.0.3987.87 (Official Build) (64-bit) on a Mac running 10.14.3 (18D109)

Using a previous commit of FileSaver.js fixes the problem and my files are downloaded using the correct filename in the script.

### PR DESCRIPTION
**Pull request by rajivshah3**
Reverts eligrey/FileSaver.js#613, which broke file saving in Chrome. I'll try to figure out a different way to solve file saving for my use case

Fixes #624

### CODE REVIEW

**Comment by rajivshah3** [comment]
@jimmywarting @eligrey sorry about that. Would you mind reviewing this when you get a chance?

**Comment by eligrey** [comment]
lgtm

**Comment by eligrey** [comment]
lgtm. I'm waiting on approval from @jimmywarting before I merge this.

**Comment by rajivshah3** [comment]
I think I'm able to fully fix this in #652

**Review by alisaeed47 — COMMENTED** [review]
A

**Pull request closed without merging**
