### PR TITLE
Added bower.json file for bower.io support. See addl instructions below:

### PR DESCRIPTION
**Pull request by grempe**
Addresses issue: https://github.com/eligrey/FileSaver.js/issues/127

See : http://bower.io/docs/creating-packages/

TODO :

  * Commit this pull request in the main repo.
  * Commit a git tag with the version number from bower.json with `git tag -a 0.0.1 GIT_SHA1_OF_LAST_COMMIT -m "Add git version number tag for bower.io registration."`
  * `git push && git push --tags`
  * Register with bower.io with `bower register FileSaver.js git://github.com/eligray/FileSaver.js.git`

### CODE REVIEW

**Comment by kdela** [comment]
@eligrey +1.

**Comment by mactkg** [comment]
:+1: @eligrey

**Comment by paulwithap** [comment]
+1

**Comment by mansona** [comment]
Has there been any movement on this?

**Comment by davepreston** [comment]
+1

**Comment by carlos-algms** [comment]
Hello every one, I forked this repo and applied all PRs that are not accept yet and published it into bower.
You can install it using: ```bower install FileSaver.js```.
I also cleaned up the code to make it easy to maintain.

**Comment by Flimm** [comment]
Nice, although now it looks like we have two forks, [yours](https://github.com/carlos-algms/FileSaver.js), and [one linked from this repo's README](http://github.com/Teleborder/FileSaver.js).

**Pull request closed without merging**
