### PR TITLE
Fix RollUp-Error because of This is Undefined Rewrite

### PR DESCRIPTION
**Pull request by arasabbasi**
make it compatible with RollUp
rollup/rollup#759
MrRio/jsPDF#1533

### CODE REVIEW

**Comment by eligrey** [comment]
See https://github.com/eligrey/Blob.js/pull/56#issuecomment-357120358

I don't need `this.content || this`, so you can just remove it entirely. Once you've made that change I will merge this.

**Comment by eligrey** [comment]
Actually, just `|| this` is fine, and shouldn't cause any rollup errors. Don't forget to also increment [the version number and timestamp](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L3-L4) at the top to 1.3.4 and 2017-01-12. Then I will merge this.

**Comment by eligrey** [comment]
Oops, I merged with `this.content` still. I'll fix that.

**Comment by arasabbasi** [comment]
Thank you!

**Pull request merged**
