### PR TITLE
fix: Refine macOS WebView check so that it is false for browsers

### LINKED ISSUE #624: Latest commit breaks file download in Chrome
This recent commit (https://github.com/eligrey/FileSaver.js/commit/7a8ff3cc6ae717b6c7628b3c280a5c593c2206ee) has broken downloads in Chrome. 

When I use the script from Tampermonkey to download a text file a new tab opens with the text "downloading..." and the file is downloaded with the generic filename "download", ignoring the filename set in the script.

I'm using Chrome Version 80.0.3987.87 (Official Build) (64-bit) on a Mac running 10.14.3 (18D109)

Using a previous commit of FileSaver.js fixes the problem and my files are downloaded using the correct filename in the script.

### PR DESCRIPTION
**Pull request by rajivshah3**
Refines check for macOS WebViews (originally implemented in #613) so that it is `false` for Chrome, Safari, etc.

User agent for WebView: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko)`

Any browser running on macOS will have a similar user agent, but will also have one of these differences ([source](https://www.whatismybrowser.com/guides/the-latest-user-agent/macos)):
- Firefox does not have `AppleWebKit` in the string
- Chrome, Safari, Edge, Opera, Vivaldi, etc will also include `Safari`

Additionally, this is restricted to macOS (will be `false` on iOS) by testing for `Macintosh`

This fix is a bit more comprehensive, as #629 and #637 will still be `true` for Safari 

Fixes #624

### CODE REVIEW

**Comment by o-alexandrov** [comment]
Please let us know when do you plan to release it to npm?

**Comment by crgeee** [comment]
@eligrey  @rajivshah3  is this going to be released?

**Comment by rajivshah3** [comment]
I'm not a maintainer so I'm not really sure

**Comment by crgeee** [comment]
@jimmywarting I saw you made a new release but not seeing it published - https://www.npmjs.com/package/file-saver. Is the latest version available in another package registry?

**Pull request merged**
