### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by dbunker**

### CODE REVIEW

**Comment by codefo** [comment]
When this pull request will be merged, and FileSaver will be available from npm?

**Comment by dbunker** [comment]
Switched name to FileSaver.js to match the Bower pull. Not sure when this'll get merged, but you can add `"FileSaver.js": "git://github.com/dbunker/FileSaver.js.git"` to dependencies in your package.json temporarily. Could also do a separate fork if you want to have npm download from your own FileSaver.js repo.

**Comment by stbaer** [comment]
+1

**Comment by codefo** [comment]
@dbunker Yep, I know how to load dependency from git, thanks!

**Comment by ai** [comment]
@eligrey I need it too

**Comment by tuchk4** [comment]
+1

**Comment by ai** [comment]
@eligrey any updates? How we can hep with this PR?

**Comment by carlos-algms** [comment]
Hello everyone, I forked this repo and applied this PR, since the maintainer does not accept any.
Unfortunately some one already published his own version of FileSaver to NPM, but it is out of date.
To install it via NPM use "html5-filesaver.js", this version have all PRs from this repo and some others updates.

**Comment by bbottema** [comment]
That's a shame. Why is this project not cooperating with the Open Source community?

**Comment by eligrey** [comment]
https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L3 is the version number. Also, the license isn't ISC.

@bbottema It's MIT licensed so you can easily upload any version to npm.

**Comment by madhums** [comment]
seriously?!

**Comment by eligrey** [comment]
@madhums FileSaver.js is available for npm, along with any other package managers of your choosing. I am not restricting you from npm.

**Pull request closed without merging**
