### PR TITLE
Don't ignore the minified file in bower.json

### PR DESCRIPTION
**Pull request by sjurba**

### CODE REVIEW

**Comment by sjurba** [comment]
Thanx. Do you mind kicking off a new release as well, as our build is currently broken.. Otherwise I'll have to fiddle with using my own fork until you do..

**Comment by jimmywarting** [comment]
Think we will soon release 1.3.0 when #233 has been removed. Maybe you can use the unminified version until then

**Comment by rur** [comment]
@sjurba I suggest you specify exact versions in your bowser.json for all dependencies so patches like this don't break your build unexpectedly ("1.2.0" in this case). Sucks to have a build crash and burn for this reason during a vacation or weekend ops maintenance!

**Comment by sjurba** [comment]
No worries. 😊

**Pull request merged**
